-- Clear and repopulate equation_codes with ONLY approved Phototheology symbols

TRUNCATE TABLE equation_codes;

-- FLOOR 1 — FURNISHING
INSERT INTO equation_codes (code, name, category, description, floor_association) VALUES
('SR', 'Story Room', 'floor1', 'Store Bible stories as vivid mental movies', 'Floor 1 - Furnishing'),
('IR', 'Imagination Room', 'floor1', 'Step inside stories with immersive imagination', 'Floor 1 - Furnishing'),
('24', '24FPS Room', 'floor1', 'One symbolic image per chapter', 'Floor 1 - Furnishing'),
('F01', 'Frame 01', 'floor1_frames', '24FPS Frame 1', 'Floor 1 - 24FPS'),
('F02', 'Frame 02', 'floor1_frames', '24FPS Frame 2', 'Floor 1 - 24FPS'),
('F03', 'Frame 03', 'floor1_frames', '24FPS Frame 3', 'Floor 1 - 24FPS'),
('F04', 'Frame 04', 'floor1_frames', '24FPS Frame 4', 'Floor 1 - 24FPS'),
('F05', 'Frame 05', 'floor1_frames', '24FPS Frame 5', 'Floor 1 - 24FPS'),
('F06', 'Frame 06', 'floor1_frames', '24FPS Frame 6', 'Floor 1 - 24FPS'),
('F07', 'Frame 07', 'floor1_frames', '24FPS Frame 7', 'Floor 1 - 24FPS'),
('F08', 'Frame 08', 'floor1_frames', '24FPS Frame 8', 'Floor 1 - 24FPS'),
('F09', 'Frame 09', 'floor1_frames', '24FPS Frame 9', 'Floor 1 - 24FPS'),
('F10', 'Frame 10', 'floor1_frames', '24FPS Frame 10', 'Floor 1 - 24FPS'),
('F11', 'Frame 11', 'floor1_frames', '24FPS Frame 11', 'Floor 1 - 24FPS'),
('F12', 'Frame 12', 'floor1_frames', '24FPS Frame 12', 'Floor 1 - 24FPS'),
('F13', 'Frame 13', 'floor1_frames', '24FPS Frame 13', 'Floor 1 - 24FPS'),
('F14', 'Frame 14', 'floor1_frames', '24FPS Frame 14', 'Floor 1 - 24FPS'),
('F15', 'Frame 15', 'floor1_frames', '24FPS Frame 15', 'Floor 1 - 24FPS'),
('F16', 'Frame 16', 'floor1_frames', '24FPS Frame 16', 'Floor 1 - 24FPS'),
('F17', 'Frame 17', 'floor1_frames', '24FPS Frame 17', 'Floor 1 - 24FPS'),
('F18', 'Frame 18', 'floor1_frames', '24FPS Frame 18', 'Floor 1 - 24FPS'),
('F19', 'Frame 19', 'floor1_frames', '24FPS Frame 19', 'Floor 1 - 24FPS'),
('F20', 'Frame 20', 'floor1_frames', '24FPS Frame 20', 'Floor 1 - 24FPS'),
('F21', 'Frame 21', 'floor1_frames', '24FPS Frame 21', 'Floor 1 - 24FPS'),
('F22', 'Frame 22', 'floor1_frames', '24FPS Frame 22', 'Floor 1 - 24FPS'),
('F23', 'Frame 23', 'floor1_frames', '24FPS Frame 23', 'Floor 1 - 24FPS'),
('F24', 'Frame 24', 'floor1_frames', '24FPS Frame 24', 'Floor 1 - 24FPS'),
('BR', 'Bible Rendered Room', 'floor1', 'Master image per 24-chapter block', 'Floor 1 - Furnishing'),
('TR', 'Translation Room', 'floor1', 'Convert verses into concrete images', 'Floor 1 - Furnishing'),
('GR', 'Gems Room', 'floor1', 'Store powerful insights and discoveries', 'Floor 1 - Furnishing'),

-- FLOOR 2 — INVESTIGATION
('OR', 'Observation Room', 'floor2', 'Notice and log details without interpretation', 'Floor 2 - Investigation'),
('DC', 'Def+Comp Room', 'floor2', 'Definitions and commentary analysis', 'Floor 2 - Investigation'),
('ST', 'Symbols/Types Room', 'floor2', 'Gods universal language and shadows of Christ', 'Floor 2 - Investigation'),
('QB', 'Questions Room', 'floor2', 'Ask relentless questions until truth emerges', 'Floor 2 - Investigation'),
('QA', 'Q&A Chains Room', 'floor2', 'Scripture answering Scripture', 'Floor 2 - Investigation'),

-- FLOOR 3 — FREESTYLE
('NF', 'Nature Freestyle', 'floor3', 'See lessons in nature and creation', 'Floor 3 - Freestyle'),
('PF', 'Personal Freestyle', 'floor3', 'Use life experiences as object lessons', 'Floor 3 - Freestyle'),
('BF', 'Bible Freestyle', 'floor3', 'Verse genetics - connecting verses', 'Floor 3 - Freestyle'),
('HF', 'History/Social Freestyle', 'floor3', 'See lessons in culture and history', 'Floor 3 - Freestyle'),
('LR', 'Listening Room', 'floor3', 'Turn conversations into connections', 'Floor 3 - Freestyle'),

-- FLOOR 4 — NEXT LEVEL
('CR', 'Concentration Room', 'floor4', 'Every text must reveal Christ', 'Floor 4 - Next Level'),
('DR', 'Dimensions Room', 'floor4', 'Five dimensions of interpretation', 'Floor 4 - Next Level'),
('1D', 'Literal Dimension', 'floor4_dimensions', 'What the text literally means', 'Floor 4 - Dimensions'),
('2D', 'Christ Dimension', 'floor4_dimensions', 'How the text points to Jesus', 'Floor 4 - Dimensions'),
('3D', 'Personal Dimension', 'floor4_dimensions', 'How it applies to me', 'Floor 4 - Dimensions'),
('4D', 'Church Dimension', 'floor4_dimensions', 'How it applies to the church', 'Floor 4 - Dimensions'),
('5D', 'Heaven Dimension', 'floor4_dimensions', 'How it applies to heaven', 'Floor 4 - Dimensions'),
('C6', 'Connect-6 Room', 'floor4', 'Six genre classifications', 'Floor 4 - Next Level'),
('Pr', 'Prophecy Genre', 'floor4_genres', 'Prophetic texts with symbols and codes', 'Floor 4 - Connect-6'),
('Pa', 'Parable Genre', 'floor4_genres', 'Simple stories with hidden depth', 'Floor 4 - Connect-6'),
('Ep', 'Epistle Genre', 'floor4_genres', 'Logical argument and doctrine', 'Floor 4 - Connect-6'),
('Hi', 'History Genre', 'floor4_genres', 'Events with theological undertones', 'Floor 4 - Connect-6'),
('Go', 'Gospel Genre', 'floor4_genres', 'Narrative focused on Christs life', 'Floor 4 - Connect-6'),
('Po', 'Poetry Genre', 'floor4_genres', 'Metaphor, rhythm, parallelism', 'Floor 4 - Connect-6'),
('TRM', 'Theme Room', 'floor4', 'Great walls and ceilings of biblical architecture', 'Floor 4 - Next Level'),
('|S', 'Sanctuary Wall', 'floor4_themes', 'Texts connecting to sanctuary system', 'Floor 4 - Theme'),
('|LC', 'Life of Christ Wall', 'floor4_themes', 'Texts anchored in Christs ministry', 'Floor 4 - Theme'),
('|GC', 'Great Controversy Wall', 'floor4_themes', 'Cosmic battle between Christ and Satan', 'Floor 4 - Theme'),
('|TP', 'Time Prophecy Wall', 'floor4_themes', 'Texts tied to prophetic timelines', 'Floor 4 - Theme'),
('\G', 'Gospel Floor', 'floor4_themes', 'Base of all truth - justification, sanctification', 'Floor 4 - Theme'),
('\H', 'Heaven Ceiling', 'floor4_themes', 'Final hope - new creation, eternal life', 'Floor 4 - Theme'),
('TZ', 'Time Zone Room', 'floor4', 'Locate texts across past, present, future', 'Floor 4 - Next Level'),
('Hpa', 'Heaven Past', 'floor4_timezones', 'Heavenly realm in the past', 'Floor 4 - Time Zone'),
('Hp', 'Heaven Present', 'floor4_timezones', 'Heavenly realm in the present', 'Floor 4 - Time Zone'),
('Hf', 'Heaven Future', 'floor4_timezones', 'Heavenly realm in the future', 'Floor 4 - Time Zone'),
('Epa', 'Earth Past', 'floor4_timezones', 'Earthly realm in the past', 'Floor 4 - Time Zone'),
('En', 'Earth Now', 'floor4_timezones', 'Earthly realm in the present', 'Floor 4 - Time Zone'),
('Ef', 'Earth Future', 'floor4_timezones', 'Earthly realm in the future', 'Floor 4 - Time Zone'),
('≈', 'Patterns Room', 'floor4', 'Gods recurring fingerprints across Scripture', 'Floor 4 - Next Level'),
('∥', 'Parallels Room', 'floor4', 'Mirrored actions across time', 'Floor 4 - Next Level'),
('FRT', 'Fruit Room', 'floor4', 'Test all interpretation by its fruit', 'Floor 4 - Next Level'),
('-lv', 'Love Fruit', 'floor4_fruit', 'Galatians 5:22 - Love', 'Floor 4 - Fruit'),
('-j', 'Joy Fruit', 'floor4_fruit', 'Galatians 5:22 - Joy', 'Floor 4 - Fruit'),
('-p', 'Peace Fruit', 'floor4_fruit', 'Galatians 5:22 - Peace', 'Floor 4 - Fruit'),
('-ls', 'Longsuffering Fruit', 'floor4_fruit', 'Galatians 5:22 - Patience', 'Floor 4 - Fruit'),
('-ge', 'Gentleness Fruit', 'floor4_fruit', 'Galatians 5:22 - Kindness', 'Floor 4 - Fruit'),
('-g', 'Goodness Fruit', 'floor4_fruit', 'Galatians 5:22 - Goodness', 'Floor 4 - Fruit'),
('-f', 'Faith Fruit', 'floor4_fruit', 'Galatians 5:22 - Faith', 'Floor 4 - Fruit'),
('-m', 'Meekness Fruit', 'floor4_fruit', 'Galatians 5:22 - Meekness', 'Floor 4 - Fruit'),
('-t', 'Temperance Fruit', 'floor4_fruit', 'Galatians 5:22 - Self-control', 'Floor 4 - Fruit'),

-- FLOOR 5 — VISION
('BL', 'Blue Room', 'floor5', 'Sanctuary as blueprint of salvation', 'Floor 5 - Vision'),
('SAN-ALT', 'Altar of Burnt Offering', 'floor5_sanctuary', 'The cross - sacrifice', 'Floor 5 - Sanctuary'),
('SAN-LAVER', 'Laver', 'floor5_sanctuary', 'Baptism and cleansing', 'Floor 5 - Sanctuary'),
('SAN-BREAD', 'Table of Shewbread', 'floor5_sanctuary', 'Word of God', 'Floor 5 - Sanctuary'),
('SAN-LAMP', 'Lampstand', 'floor5_sanctuary', 'Light of the Spirit', 'Floor 5 - Sanctuary'),
('SAN-INCENSE', 'Altar of Incense', 'floor5_sanctuary', 'Intercession and prayer', 'Floor 5 - Sanctuary'),
('SAN-ARK', 'Ark/Mercy Seat', 'floor5_sanctuary', 'Law, mercy seat, Gods throne', 'Floor 5 - Sanctuary'),
('PR', 'Prophecy Room', 'floor5', 'Telescope lens of prophetic timelines', 'Floor 5 - Vision'),
('@120', '120 Years', 'floor5_prophecy', 'Genesis 6:3 - time before flood', 'Floor 5 - Prophecy'),
('@400', '400 Years', 'floor5_prophecy', 'Genesis 15:13 - Egypt bondage', 'Floor 5 - Prophecy'),
('@70y', '70 Years', 'floor5_prophecy', 'Jeremiah 25:11 - Babylonian captivity', 'Floor 5 - Prophecy'),
('@70w', '70 Weeks', 'floor5_prophecy', 'Daniel 9:24 - Messiah prophecy', 'Floor 5 - Prophecy'),
('@1260', '1260 Days/Years', 'floor5_prophecy', 'Revelation 12:6 - prophetic period', 'Floor 5 - Prophecy'),
('@2300', '2300 Days', 'floor5_prophecy', 'Daniel 8:14 - sanctuary cleansed', 'Floor 5 - Prophecy'),
('3A', 'Three Angels Room', 'floor5', 'Final gospel syllabus', 'Floor 5 - Vision'),
('3AM-1', 'First Angel', 'floor5_angels', 'Everlasting gospel - worship Creator', 'Floor 5 - Three Angels'),
('3AM-2', 'Second Angel', 'floor5_angels', 'Babylon is fallen', 'Floor 5 - Three Angels'),
('3AM-3', 'Third Angel', 'floor5_angels', 'Warning against beast, image, mark', 'Floor 5 - Three Angels'),
('FE', 'Feasts Room', 'floor5', 'Appointed times pointing to Christ', 'Floor 5 - Vision'),
('FE-PA', 'Passover', 'floor5_feasts', 'Christ our Passover Lamb', 'Floor 5 - Feasts'),
('FE-UN', 'Unleavened Bread', 'floor5_feasts', 'Sinless life of Christ', 'Floor 5 - Feasts'),
('FE-FI', 'Firstfruits', 'floor5_feasts', 'Christ risen as firstfruits', 'Floor 5 - Feasts'),
('FE-PE', 'Pentecost', 'floor5_feasts', 'Outpouring of Holy Spirit', 'Floor 5 - Feasts'),
('FE-TR', 'Trumpets', 'floor5_feasts', 'Warning and preparation', 'Floor 5 - Feasts'),
('FE-AT', 'Day of Atonement', 'floor5_feasts', 'Judgment and cleansing', 'Floor 5 - Feasts'),
('FE-TA', 'Tabernacles', 'floor5_feasts', 'God dwelling with His people', 'Floor 5 - Feasts'),
('CEC', 'Christ in Every Chapter', 'floor5', 'Trace Christs line in every chapter', 'Floor 5 - Vision'),
('R66', 'Room 66', 'floor5', 'One theme through all 66 books', 'Floor 5 - Vision'),

-- FLOOR 6 — THREE HEAVENS & CYCLES
('DoL¹/NE¹', 'First Day of the LORD', 'floor6_heavens', 'Babylon destruction to restoration', 'Floor 6 - Three Heavens'),
('DoL²/NE²', 'Second Day of the LORD', 'floor6_heavens', '70 AD and New Covenant order', 'Floor 6 - Three Heavens'),
('DoL³/NE³', 'Third Day of the LORD', 'floor6_heavens', 'Final cosmic renewal', 'Floor 6 - Three Heavens'),
('8C', 'Eight Cycles Room', 'floor6', 'Eight great redemption cycles', 'Floor 6 - Cycles'),
('@Ad', 'Adamic Cycle', 'floor6_cycles', 'Eden to Promise', 'Floor 6 - Eight Cycles'),
('@Se', 'Seth Cycle', 'floor6_cycles', 'Worship continues after Cain', 'Floor 6 - Eight Cycles'),
('@No', 'Noahic Cycle', 'floor6_cycles', 'Flood to Covenant', 'Floor 6 - Eight Cycles'),
('@Ab', 'Abrahamic Cycle', 'floor6_cycles', 'Call to Covenant People', 'Floor 6 - Eight Cycles'),
('@Mo', 'Mosaic Cycle', 'floor6_cycles', 'Exodus to Sanctuary Nation', 'Floor 6 - Eight Cycles'),
('@Cy', 'Cyrusic Cycle', 'floor6_cycles', 'Exile to Return and Rebuild', 'Floor 6 - Eight Cycles'),
('@Sp', 'Holy Spirit Cycle', 'floor6_cycles', 'Pentecost to Revivals', 'Floor 6 - Eight Cycles'),
('@Re', 'Remnant Cycle', 'floor6_cycles', 'End-time witness to Second Coming', 'Floor 6 - Eight Cycles'),
('JR', 'Juice Room', 'floor6', 'Squeeze one book with all principles', 'Floor 6 - Cycles'),

-- FLOOR 7 — SPIRITUAL & EMOTIONAL
('FRM', 'Fire Room', 'floor7', 'Emotional weight and conviction', 'Floor 7 - Spiritual'),
('MR', 'Meditation Room', 'floor7', 'Slow marination in truth', 'Floor 7 - Spiritual'),
('SRM', 'Speed Room', 'floor7', 'Rapid application and reflexes', 'Floor 7 - Spiritual');